POST http://localhost:8000/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3NjkyNDg1MDMsImV4cCI6MTc2OTI0OTQwM30.2twKVFWH55_HK16PfiGclZ3yOS6chewtIWPIOxof0dU